lsi: false
safe: true
title: Holger Woltersdorf
description: Website of Holger Woltersdorf
ignore_theme_config: true
timezone: "Europe/Berlin"
encoding: utf-8
strict_front_matter: true
url: "https://hollo.me"
keep_files: [.gitkeep]
markdown: kramdown
exclude: [CHANGELOG.md, Makefile, .idea/workspace.xml]