version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      only:
        - test/circleci
    steps:
      - checkout
      - run: apt-get install rssh -y
      - run:
          name: Greeting
          command: echo "Hello, world."
      - add_ssh_keys
      - deploy:
          command: |
            scp -oStrictHostKeyChecking=no -r ~/project/* deploy@hollo.me:/var/www/deploy-test/
