version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    branches:
      only:
        - test/circleci
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "Hello, world."
      - deploy:
          command: scp -r circle-pushing/* deploy@hollo.me:/var/www/deploy-test/
