version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "Hello, world."
  deployment:
    dev:
      branch: test/circleci
      commands:
        - scp -r circle-pushing/* deploy@hollo.me:/var/www/deploy-test/

